/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import cronometro.CronometroListener;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import logica.Carrera;
import logica.Corredor;
import logica.LogicaNegocio;

/**
 *
 * @author Pelayo
 */
public class GestionCarrera extends javax.swing.JDialog {

    private LogicaNegocio logica;
    private Carrera ca;//
    private PantallaCarreras pc;

    public GestionCarrera(java.awt.Frame parent, boolean modal, LogicaNegocio ln, Carrera c, PantallaCarreras pc) {
        super(parent, modal);
        initComponents();
        logica = ln;
        ca = c;
        this.pc = pc;
        rellenarLista();
        GestionCarrera gc = this;
        
        
        cronometro1.setCronometroListener(new CronometroListener() {
            @Override
            public void resgistrarTiempo() {
                int seleccionado = jListCorredores.getSelectedIndex();
                Corredor corredorSeleccionado = null;
                if (seleccionado == -1) {
                    JOptionPane.showMessageDialog(null, "Tienes que seleccionar un corredor", "Titulo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    corredorSeleccionado = logica.getCarreraSelecionada().getNoFinalizados().get(seleccionado);
                    logica.getCarreraSelecionada().finalizarCarrera(corredorSeleccionado, cronometro1.getTiempo());
                     if(!logica.getCarreraSelecionada().isFinalizada()) {
                        rellenarLista();
                    }
                    else {
                         JOptionPane.showMessageDialog(null, "Todos los corredores han finalizado la carrera", "Fin de la carrera", JOptionPane.INFORMATION_MESSAGE);
                         pc.rellenarTablaCarreras();
                         logica.guardarCarrerasEnFichero();
                         logica.guardarCarreraFinalizadaEnFichero();
                         logica.setCarreraSelecionada(null);
                         gc.dispose();
                    }
                    

                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCorredores = new javax.swing.JList<>();
        cronometro1 = new cronometro.Cronometro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonIniciar.setText(org.openide.util.NbBundle.getMessage(GestionCarrera.class, "GestionCarrera.jButtonIniciar.text")); // NOI18N
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jListCorredores);

        cronometro1.setText(org.openide.util.NbBundle.getMessage(GestionCarrera.class, "GestionCarrera.cronometro1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIniciar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(cronometro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cronometro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButtonIniciar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        cronometro1.start();
        jButtonIniciar.setEnabled(false);
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void rellenarLista() {
        DefaultListModel dlm2 = new DefaultListModel();

        System.out.println(ca.getNoFinalizados());
        for (Corredor c : ca.getNoFinalizados()) {
            dlm2.addElement(c);
        }

        jListCorredores.setModel(dlm2);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private cronometro.Cronometro cronometro1;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JList<String> jListCorredores;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
