/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.Carrera;
import logica.Corredor;
import logica.LogicaNegocio;

/**
 *
 * @author Pelayo
 */
public class PantallaAltaCarrera extends javax.swing.JDialog {

    private LogicaNegocio logica;
    private int accion;
    private ArrayList<Corredor> provisionalAdd;
    private ArrayList<Corredor> provisionalDisponibles;

    /**
     * Creates new form PantallaAltaCarrera
     */
    public PantallaAltaCarrera(java.awt.Frame parent, boolean modal, LogicaNegocio ln, int accion) {
        super(parent, modal);
        logica = ln;
        this.accion = accion;

        initComponents();
        this.setLocationRelativeTo(null);

        if (accion == 1) {//Alta
            jLabelAltaCarrera.setText("Alta Carreras");
            provisionalAdd = new ArrayList<>();
            provisionalDisponibles = new ArrayList<>(logica.getListaCorredores());

        } else if (accion == 2) {//Modificar
            jLabelAltaCarrera.setText("Modificar Carreras");

            Carrera c = logica.getCarreraSelecionada();

            provisionalAdd = c.getListaCorredores();
            provisionalDisponibles = new ArrayList<>(logica.corredoresDisponiblesCarrera(c));//

            jTextFieldNombre.setText(c.getNombreCarrera());
            jSpinnerFecha.setValue(c.getFechaCarrera());
            jTextFieldLugar.setText(c.getLugarCarrera());
            jTextFieldMaximoCorredores.setText(String.valueOf(c.getMaximoCorredores()));

        }
        
        mostrarListaInscritos();
        mostrarListaDisponible();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAltaCarrera = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelLugar = new javax.swing.JLabel();
        jLabelNumMax = new javax.swing.JLabel();
        jLabelListaCorredores = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jSpinnerFecha = new javax.swing.JSpinner();
        jTextFieldLugar = new javax.swing.JTextField();
        jTextFieldMaximoCorredores = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListInscritos = new javax.swing.JList<>();
        jButtonAceptar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonInscribirCorredor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDisponibles = new javax.swing.JList<>();
        jLabelDorsal = new javax.swing.JLabel();
        jButtonBorrarCorredor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelAltaCarrera.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jLabelAltaCarrera.text")); // NOI18N

        jLabelNombre.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jLabelNombre.text")); // NOI18N

        jLabelFecha.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jLabelFecha.text")); // NOI18N

        jLabelLugar.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jLabelLugar.text")); // NOI18N

        jLabelNumMax.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jLabelNumMax.text")); // NOI18N

        jLabelListaCorredores.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jLabelListaCorredores.text")); // NOI18N

        jTextFieldNombre.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jTextFieldNombre.text")); // NOI18N

        jSpinnerFecha.setModel(new javax.swing.SpinnerDateModel());

        jTextFieldLugar.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jTextFieldLugar.text")); // NOI18N

        jTextFieldMaximoCorredores.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jTextFieldMaximoCorredores.text")); // NOI18N

        jScrollPane1.setViewportView(jListInscritos);

        jButtonAceptar.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jButtonAceptar.text")); // NOI18N
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jButtonBorrar.text")); // NOI18N
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonInscribirCorredor.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jButtonInscribirCorredor.text")); // NOI18N
        jButtonInscribirCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscribirCorredorActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jLabel1.text")); // NOI18N

        jScrollPane2.setViewportView(jListDisponibles);

        jButtonBorrarCorredor.setText(org.openide.util.NbBundle.getMessage(PantallaAltaCarrera.class, "PantallaAltaCarrera.jButtonBorrarCorredor.text")); // NOI18N
        jButtonBorrarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarCorredorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabelAltaCarrera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFecha)
                            .addComponent(jLabelLugar)
                            .addComponent(jLabelNumMax)
                            .addComponent(jLabelListaCorredores)
                            .addComponent(jLabelNombre)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAceptar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBorrar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jButtonInscribirCorredor)
                                .addGap(90, 90, 90)
                                .addComponent(jButtonBorrarCorredor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldMaximoCorredores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addComponent(jSpinnerFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldLugar, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelDorsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelAltaCarrera)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha)
                    .addComponent(jSpinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLugar)
                    .addComponent(jTextFieldLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumMax)
                    .addComponent(jTextFieldMaximoCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelListaCorredores)))
                .addGap(18, 18, 18)
                .addComponent(jLabelDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonBorrarCorredor)
                    .addComponent(jButtonInscribirCorredor))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarListaDisponible() {
        DefaultListModel dlm1 = new DefaultListModel();
        System.out.println("Disponible");

        for (Corredor c : provisionalDisponibles) {
            dlm1.addElement(c);
            System.out.println(c);
        }

        jListDisponibles.setModel(dlm1);

    }

    private void mostrarListaInscritos() {
        DefaultListModel dlm2 = new DefaultListModel();

        for (Corredor c : provisionalAdd) {
            dlm2.addElement(c);
        }

        jListInscritos.setModel(dlm2);
    }


    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        String nombre = jTextFieldNombre.getText();
        Date fecha = (Date) jSpinnerFecha.getValue();//hacer cast a fecha
        String lugar = jTextFieldLugar.getText();
        int numMax = Integer.valueOf(jTextFieldMaximoCorredores.getText());

        if (accion == 1) {//Alta    

            int resultado = JOptionPane.showConfirmDialog(this, "¿Quieres dar de alta la carrera?", "Título", JOptionPane.YES_NO_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "La carrera ha sido creada", "Titulo", JOptionPane.INFORMATION_MESSAGE);
                if (numMax < provisionalAdd.size()) {
                    int respuesta = JOptionPane.showConfirmDialog(this, "El numero indicado como máximo es inferior al numero de corredores añadidos,"
                            + " ¿deseas modificar el máximo?",
                            "Título", JOptionPane.YES_NO_OPTION);
                    if (respuesta == JOptionPane.YES_OPTION) {
                        numMax = provisionalAdd.size();
                        logica.altaCarrera(nombre, fecha, lugar, numMax, provisionalAdd);
                         this.dispose();
                    } else {
                        
                    }

                } else {
                    logica.altaCarrera(nombre, fecha, lugar, numMax, provisionalAdd);
                    this.dispose();
                }

            } else if (resultado == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Los datos de la carrera han sido borrados", "Titulo", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {//Modificar

            int resultado = JOptionPane.showConfirmDialog(this, "¿Quieres modificar la carrera?", "Título", JOptionPane.YES_NO_OPTION);
            if (resultado == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, "La carrera ha sido modificada", "Titulo", JOptionPane.INFORMATION_MESSAGE);

                logica.altaCarrera(nombre, fecha, lugar, numMax, provisionalAdd);
          
            } else if (resultado == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "La carrera  no ha sido modificada", "Titulo", JOptionPane.INFORMATION_MESSAGE);
                logica.getListaCarreras().add(logica.getCarreraSelecionada());
             
            }
            logica.setCarreraSelecionada(null);
            this.dispose();
        }

       


    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "¿Quieres borrarlo?", "Título", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "La informacion se ha borrado", "Titulo", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldNombre.setText("");
            jTextFieldLugar.setText("");
            jTextFieldMaximoCorredores.setText("");

        } else if (resultado == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "La informacion no se ha borrado", "Titulo", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonInscribirCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscribirCorredorActionPerformed
        int index = jListDisponibles.getSelectedIndex();
        if (accion == 1) { // alta

            if (index != -1) {
                provisionalAdd.add(provisionalDisponibles.get(index));
                provisionalDisponibles.remove(index);
            } else {
                JOptionPane.showMessageDialog(this, "Tienes que tener un corredor seleccionado", "Titulo", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {// modificar
            provisionalAdd.add(provisionalDisponibles.get(index));
            provisionalDisponibles.remove(index);
        }

        jListDisponibles.clearSelection();
        jListInscritos.clearSelection();
        mostrarListaDisponible();
        mostrarListaInscritos();

    }//GEN-LAST:event_jButtonInscribirCorredorActionPerformed

    private void jButtonBorrarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarCorredorActionPerformed
        int index = jListInscritos.getSelectedIndex();
        if (accion == 1) { // alta

            if (index != -1) {
                provisionalDisponibles.add(provisionalAdd.get(index));
                provisionalAdd.remove(index);

            } else {
                JOptionPane.showMessageDialog(this, "Tienes que tener un corredor seleccionado", "Titulo", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            provisionalDisponibles.add(provisionalAdd.get(index));
            provisionalAdd.remove(index);
        }

        jListDisponibles.clearSelection();
        jListInscritos.clearSelection();
        mostrarListaDisponible();
        mostrarListaInscritos();

    }//GEN-LAST:event_jButtonBorrarCorredorActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBorrarCorredor;
    private javax.swing.JButton jButtonInscribirCorredor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAltaCarrera;
    private javax.swing.JLabel jLabelDorsal;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelListaCorredores;
    private javax.swing.JLabel jLabelLugar;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumMax;
    private javax.swing.JList<String> jListDisponibles;
    private javax.swing.JList<String> jListInscritos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerFecha;
    private javax.swing.JTextField jTextFieldLugar;
    private javax.swing.JTextField jTextFieldMaximoCorredores;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
